name: Pull Request

on:
  pull_request:

jobs:
  skip:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          paths_ignore: '["**.md", ".github/**"]'

  build:
    runs-on: ubuntu-latest
    needs: skip
    if: needs.skip.outputs.should_skip == 'false'
    steps:
      - name: Run a one-line script
        run: echo Hello, world!